INSERT INTO trains (id, line)
VALUES (1, 'Avanti West Coast'),
       (2, 'Bakerloo'),
       (3, 'c2c'),
       (4, 'Central'),
       (5, 'Chiltern Railways'),
       (6, 'Circle'),
       (7, 'CrossCountry'),
       (8, 'District'),
       (9, 'DLR'),
       (10, 'East Midlands Railway'),
       (11, 'Elizabeth line'),
       (12, 'Gatwick Express'),
       (13, 'Grand Central'),
       (14, 'Greater Anglia'),
       (15, 'Great Northern'),
       (16, 'Great Western Railway'),
       (17, 'Hammersmith & City'),
       (18, 'Heathrow Express'),
       (19, 'Hull Trains'),
       (20, 'Island Line'),
       (21, 'Jubilee'),
       (22, 'Liberty'),
       (23, 'Lioness'),
       (24, 'London North Eastern Railway'),
       (25, 'Lumo'),
       (26, 'Merseyrail'),
       (27, 'Metropolitan'),
       (28, 'Mildmay'),
       (29, 'Northern'),
       (30, 'Northern Rail'),
       (31, 'Piccadilly'),
       (32, 'ScotRail'),
       (33, 'Southeastern'),
       (34, 'Southern'),
       (35, 'South Western Railway'),
       (36, 'Suffragette'),
       (37, 'Thameslink'),
       (38, 'TransPennine Express'),
       (39, 'Transport for Wales'),
       (40, 'Victoria'),
       (41, 'Waterloo & City'),
       (42, 'Weaver'),
       (43, 'West Midlands Trains'),
       (44, 'Windrush') ON CONFLICT DO NOTHING;