name: Build and Deploy TFL Alerts

env:
  APP_NAME: tfl-alerts
  GO_VERSION: 1.23.1

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make build

      - name: Test
        run: make test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment Version
        id: versioning
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(major)"
          minor_pattern: "(minor)"
          version_format: "${major}.${minor}.${increment}"

      - name: Add version to environment
        run: echo "APP_VERSION=${{ steps.versioning.outputs.version }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}

      - name: Create .env File
        run: |
          echo "Generating .env file"

          echo "# Autogenerated .env file" > .env
          echo "APP_VERSION=${{ env.APP_VERSION }}" >> .env
          echo "REGISTRY=${{ secrets.DOCKER_USERNAME }}" >> .env

      - name: Copy Files To Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOYMENT_SSH_HOST }}
          username: ${{ secrets.DEPLOYMENT_SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          source: "./docker-compose.yml,./.env"
          target: "~/${{ github.event.repository.name }}/"

      - name: Start Application
        uses: appleboy/ssh-action@v1.2.0
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        with:
          host: ${{ secrets.DEPLOYMENT_SSH_HOST }}
          username: ${{ secrets.DEPLOYMENT_SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            cd ~/${{ github.event.repository.name }}
            sudo docker compose up -d
            sudo docker system prune -f 
            sudo docker images -a | grep -v "${{ env.APP_VERSION }}" | awk '{print $1 ":" $2}' | xargs sudo docker rmi
